version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: go_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: golang:1.25-alpine
    container_name: go_api_dev
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: products
      APP_PATH: ./cmd      # <<--- AQUI
    volumes:
      - .:/app
      - go_pkg:/go/pkg/mod
      - go_build:/root/.cache/go-build
    ports:
      - "8080:8080"
    command: |
      sh -c "apk add --no-cache git build-base tzdata && \
             go install github.com/air-verse/air@latest && \
             air -c .air.toml"
    restart: unless-stopped

volumes:
  mysql_data:
  go_pkg:
  go_build:
